--CREATE DATABASE TripsDb
--USE TripsDb
CREATE TABLE [User](
ID INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
FirstName NVARCHAR(20),
LastName NVARCHAR(50) NOT NULL,
[Address] NVARCHAR(100),
PhoneNumber INT,
DOB DATE,
);

CREATE TABLE Passport(
IdNumber INT PRIMARY KEY NOT NULL,
Expiration DATE, 
[Address] NVARCHAR(100),
UserID INT FOREIGN KEY REFERENCES [User](ID) NOT NULL
);

CREATE TABLE Trip(
ID INT PRIMARY KEY IDENTITY(5, 5) NOT NULL,
Budget Decimal(10, 2),
StartDestination NVARCHAR(30) NOT NULL,
EndDestination NVARCHAR(30),
StartDate DATE,
EndDate DATE,
UserID INT FOREIGN KEY REFERENCES [User](ID) NOT NULL	
);

CREATE TABLE Hotel(
ID INT PRIMARY KEY IDENTITY(10, 10) NOT NULL,
HotelName NVARCHAR (50) NOT NULL,
[Address] NVARCHAR (100),
Phone INT,
Cost DECIMAL(10,2)
);

CREATE TABLE TripHotel(
ID INT PRIMARY KEY IDENTITY (2, 2) NOT NULL,
CheckIn DATE NOT NULL,
CheckOut DATE NOT NULL,
TripID INT FOREIGN KEY REFERENCES Trip(ID) NOT NULL,
HotelID INT FOREIGN KEY REFERENCES Hotel(ID) NOT NULL
);